export * from './user-management/user-management-dialog.component';
export * from './user-management/user-management-delete-dialog.component';
export * from './user-management/user-management-detail.component';
export * from './user-management/user-management.component';
export * from './user-management/user-management.route';
export * from './user-management/user-modal.service';
export * from './stock-management/stock-management.route';
export * from './stock-management/stock-management.component';
export * from './admin.route';
